# Generated by Django 4.1.7 on 2023-03-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('item_type', models.CharField(choices=[('company', 'Company'), ('department', 'Department'), ('employee', 'Employee')], max_length=20)),
                ('attributes', models.JSONField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('id', 'path')},
            },
        ),
    ]
