# Generated by Django 4.1.7 on 2023-03-22 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TreeAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Node',
        ),
        migrations.AlterUniqueTogether(
            name='node',
            unique_together=set(),
        ),
    ]
