# Generated by Django 4.1.7 on 2023-03-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TreeAPI', '0002_rename_project_node_alter_node_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='item_type',
            field=models.CharField(choices=[('company', 'Company'), ('department', 'Department'), ('employee', 'Employee')], max_length=100),
        ),
    ]
